#!/usr/bin/env node

/*jslint node: true */
'use strict';

var path = require('path'),
	exec = require('./lib/exec'),
    execsudo = require('./lib/execsudo');

console.log('--- Starting installation of fastlane.tools ---');
console.log('--- This can take several minutes, may we suggest a cup of coffee :D ---');

exec('ruby', ['-v'], null, function(e) {

	console.log('--- Working on produce ---');

	execsudo(['gem','install', 'produce'], null, function(e) {

		console.log('--- Working on sigh ---');

		execsudo(['gem','install', 'sigh'], null, function(e) {

			console.log('--- Working on deliver ---');

			execsudo(['gem','install', 'deliver'], null, function(e) {
				console.info('All Done.');
			});
			
		});

	});

});