#!/usr/bin/env node

/*jslint node: true */
'use strict';

var exec = require('./lib/exec');

console.log('--- Special Thanks to KrauseFx for make all this possible with Fastlane Tools ---');
console.log('--- Installing Deliver, Sigh, Produce, Pem, Snapshot, Pilot, Supply ---\n');
console.log('--- This can take several minutes, may we suggest a cup of coffee :D ---\n');

exec('gem',['install', 'deliver', 'sigh', 'produce', 'pem', 'snapshot', 'pilot', 'supply'], null, function(e) {
	console.log('--- All Tools Downloaded ---');
});
