#!/usr/bin/env node

/*jslint node: true */
'use strict';

var path = require('path'),
	exec = require('./lib/exec'),
    execsudo = require('./lib/execsudo');

console.log('--- Starting installation of fastlane.tools ---');
console.log('--- This can take several minutes, may we suggest a cup of coffee :D ---');

exec('ruby', ['-v'], null, function(e) {

	execsudo(['gem','install', 'fastlane'], null, function(e) {
		
		console.log('--- All Tools Downloaded ---');

	});

});
